### ISSUE TITLE
Add endpoint for todo crud

### ISSUE THREAD

**Issue by grygy** [grygy/another-todo-app#8]
- [x] add get todo by logged user endpoint
- [x] add create todo endpoint
- [x] add mark todo as done endpoint
